### Client 1
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

### preencher o ID retornado
@clientID1 = "93aedea1-4357-4b49-afcf-1f67e1dd431c"

### Client 2
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

### preencher o ID retornado
@clientID2 = "191e617f-e002-4fab-b246-b52f4a9f9cb9"

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": {{clientID1}}
}

### preencher o ID retornado
@accountID1 = "a3b37c32-0e31-4ed5-a089-a05ec62e885f"

###
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": {{clientID2}}
}

### preencher com o ID retornado
@accountID2 = "a9ab7b77-fcb0-4752-92b7-a3decbc586be"

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": {{accountID1}},
    "account_id_to": {{accountID2}},
    "amount": 1
}


### example usando curl para criar client###
curl -d '{"name": "John Doe", "email": "j@j.com"}' -H 'Content-Type: application/json' -X POST http://localhost:8080/clients
